In [1]:
import numpy as np

In [24]:

x = np.array([1,34],dtype = np.float64)

In [25]:
x.view(np.uint8)

array([  0,   0,   0,   0,   0,   0, 240,  63,   0,   0,   0,   0,   0,
         0,  65,  64], dtype=uint8)

In [28]:
shape_dim1 = 1
shape_dim2 = np.array(list('pumpernickel90-B1-1C-99-F1-6620214')).shape[0]


In [33]:
asciibytearray = [ord(i) for i in list('char')]

In [67]:
np.c_[np.array(asciibytearray).reshape(1,-1),np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1)][0]

array([ 99, 104,  97, 114,   0,   0,   0,   0,   0,   0, 240,  63,   0,
         0,   0,   0,   0,   0,  65,  64])

In [58]:
type(np.append(np.array(asciibytearray).view(np.uint8)[[0,4,8,12]],np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1))[0])

numpy.uint8

In [68]:
bt_1 = np.append(np.array(asciibytearray).view(np.uint8)[[0,4,8,12]],np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1))

In [70]:
bt_1

array([ 99, 104,  97, 114,   0,   0,   0,   0,   0,   0, 240,  63,   0,
         0,   0,   0,   0,   0,  65,  64], dtype=uint8)

In [71]:
import hashlib
hashlib_object = hashlib.md5()

hashlib_object.update(bt_1)

In [72]:
hashlib_object.hexdigest()

'e7e0077c51dc30cf5f9b6b141849e6a2'

In [79]:
list(hashlib_object.digest())

[231, 224, 7, 124, 81, 220, 48, 207, 95, 155, 107, 20, 24, 73, 230, 162]