In [1]:
import numpy as np

In [2]:

x = np.array([1,34],dtype = np.float64)

In [3]:
x.view(np.uint8)

array([  0,   0,   0,   0,   0,   0, 240,  63,   0,   0,   0,   0,   0,
         0,  65,  64], dtype=uint8)

In [4]:
shape_dim1 = 1
shape_dim2 = np.array(list('pumpernickel90-B1-1C-99-F1-6620214')).shape[0]


In [5]:
asciibytearray = [ord(i) for i in list('char')]

In [6]:
np.c_[np.array(asciibytearray).reshape(1,-1),np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1)][0]

array([ 99, 104,  97, 114,   0,   0,   0,   0,   0,   0, 240,  63,   0,
         0,   0,   0,   0,   0,  65,  64])

In [7]:
type(np.append(np.array(asciibytearray).view(np.uint8)[[0,4,8,12]],np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1))[0])

numpy.uint8

In [8]:
bt_1 = np.append(np.array(asciibytearray).view(np.uint8)[[0,4,8,12]],np.array([1,34],dtype = np.float64).view(np.uint8).reshape(1,-1))

In [9]:
bt_1

array([ 99, 104,  97, 114,   0,   0,   0,   0,   0,   0, 240,  63,   0,
         0,   0,   0,   0,   0,  65,  64], dtype=uint8)

In [10]:
import hashlib
hashlib_object = hashlib.md5()

hashlib_object.update(bt_1)

In [11]:
hashlib_object.hexdigest()

'e7e0077c51dc30cf5f9b6b141849e6a2'

In [18]:
np.array(asciibytearray).dtype

dtype('int32')

In [15]:
hashlib_object.hexdigest()

'e7e0077c51dc30cf5f9b6b141849e6a2'

In [31]:
np.array([np.array(list(hashlib_object.digest())).view(np.int8)[i] for i in range(0,np.array(list(hashlib_object.digest())).view(np.int8).shape[0]) if i%4 == 0]).dtype

dtype('int8')

In [29]:
np.array(list(hashlib_object.digest())).view(np.int8).shape

(64,)

In [36]:
np.array(list(hashlib_object.digest())).dtype

dtype('int32')

In [47]:
np.array([ord(i) for i  in list('pumpernickel90-B1-1C-99-F1-6620214')]).view(np.uint16)

array([112,   0, 117,   0, 109,   0, 112,   0, 101,   0, 114,   0, 110,
         0, 105,   0,  99,   0, 107,   0, 101,   0, 108,   0,  57,   0,
        48,   0,  45,   0,  66,   0,  49,   0,  45,   0,  49,   0,  67,
         0,  45,   0,  57,   0,  57,   0,  45,   0,  70,   0,  49,   0,
        45,   0,  54,   0,  54,   0,  50,   0,  48,   0,  50,   0,  49,
         0,  52,   0], dtype=uint16)

In [48]:
final_update = np.array([np.array([ord(i) for i  in list('pumpernickel90-B1-1C-99-F1-6620214')]).view(np.uint16)[i] for i in range(0,np.array([ord(i) for i  in list('pumpernickel90-B1-1C-99-F1-6620214')]).view(np.uint16).shape[0]) if i%2 == 0]).view(np.uint8)

In [49]:
final_update

array([112,   0, 117,   0, 109,   0, 112,   0, 101,   0, 114,   0, 110,
         0, 105,   0,  99,   0, 107,   0, 101,   0, 108,   0,  57,   0,
        48,   0,  45,   0,  66,   0,  49,   0,  45,   0,  49,   0,  67,
         0,  45,   0,  57,   0,  57,   0,  45,   0,  70,   0,  49,   0,
        45,   0,  54,   0,  54,   0,  50,   0,  48,   0,  50,   0,  49,
         0,  52,   0], dtype=uint8)

In [50]:
hashlib_object.update(final_update)

In [51]:
hashlib_object.hexdigest()

'ae78c87f40094daf52ce0c8d5c3bfd41'

In [52]:
list(hashlib_object.digest())

[174, 120, 200, 127, 64, 9, 77, 175, 82, 206, 12, 141, 92, 59, 253, 65]